# p10k enabled
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# TODO: 消すか検討
#POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='$'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='$'
